### PR TITLE
Casefix

### PR DESCRIPTION
**Pull request by peardox**
Six More

Boto3 - AWS (going to test + demo)
Keras - Standard ML lib
MoviePy - Handles mp4 etc (going to test + demo)
ONNXRuntime - Converts models to ONNX (common format) - (going to test + demo)
PyQT5 - As per issue 13 - quick test raised assertion error - no setup so not sure what's up
RemBG - ML removebackground from image (going to test + demo)

Matplotlib now works (after a fashion) - initially it will raise an assertion error but subsequently will render the charts as per issue #9

### CODE REVIEW

**Comment by lmbelo** [comment]
We definitely need smaller commits 😅

**Comment by peardox** [comment]
The number of diffs you're getting appears to be down to versions we're using

I'm on 19.2 (10.4.2 CE) - packages to 270
You're on 19.4 (11.x) - packages to 280

https://github.com/omonien/Delphi-Version-Information/blob/master/README.md

**Comment by lmbelo** [comment]
> The number of diffs you're getting appears to be down to versions we're using
> 
> I'm on 19.2 (10.4.2 CE) - packages to 270 You're on 19.4 (11.x) - packages to 280
> 
> https://github.com/omonien/Delphi-Version-Information/blob/master/README.md

Are you using Project Magician? Most of those changes are IDE deal, but many we have kept, like Win32 Release as default platform and build configuration.

**Comment by peardox** [comment]
I cut + paste the dproj, dpk and pas files (H5Py is the base as it's an easy search + replace)

**Pull request merged**
