### PR TITLE
Removed underscore from CV2_Contrib

### PR DESCRIPTION
**Pull request by peardox**

### CODE REVIEW

**Comment by peardox** [comment]
Removed the underscore as requested

**Comment by lmbelo** [comment]
Ah, I made it.
Once I have time, I will create a new repository for general purpose packages and take some of that packages to it.

**Comment by peardox** [comment]
I removed the underscore from CV2_Contrib as requested but in the current repo I see it's still there

**Comment by lmbelo** [comment]
We should take it to the existing OpenCV package. Any variant or subprojects of a project should reside in only one package.

**Comment by peardox** [comment]
As I see it we need some method that would allow the selection of PropertyName from a list (usually with only one entry) to cater for this kind of situation.

As far as I can tell changing the PackageName is not catered for in the current object design (it's used in the inherited constructor). I did try altering PackageName on the fly but lack of documentation made it difficult to follow what was going on.

I also tried using the index switch system but that didn't work either - although it does work well in the case of Torch - but then that package expects an extra-url param anyway...

It would also be desirable to have a simple way to install a package you didn't need Delphi bindings for (can't figure that out either). One particularly interesting possibility that installing missing packages would allow is that you could take any random script and, with a little perseverance, almost automatically build it's dependancies without knowing them in advance  = you just trap MissingPAckage exceptions and add them to a next try pass til it works - auto-Python :)

**Comment by lmbelo** [comment]
> As I see it we need some method that would allow the selection of PropertyName from a list (usually with only one entry) to cater for this kind of situation.
> 
> As far as I can tell changing the PackageName is not catered for in the current object design (it's used in the inherited constructor). I did try altering PackageName on the fly but lack of documentation made it difficult to follow what was going on.
> 
> I also tried using the index switch system but that didn't work either - although it does work well in the case of Torch - but then that package expects an extra-url param anyway...
> 
> It would also be desirable to have a simple way to install a package you didn't need Delphi bindings for (can't figure that out either). One particularly interesting possibility that installing missing packages would allow is that you could take any random script and, with a little perseverance, almost automatically build it's dependancies without knowing them in advance = you just trap MissingPAckage exceptions and add them to a next try pass til it works - auto-Python :)

The "PackageName" property is package exclusive and must not be changed. That was made intentionally, otherwise it wouldn't make sense to create new components linking to other packages.

I have used the extra-index-url and it works fine.

I also thought to create some sort of "global" component that supports any package. 

BTW, we definitely need a new repository for non-dsc or general purpose components. I will work out on it when possible.

**Comment by lmbelo** [comment]
Ahh, can you try my OpenCVContrib variant?

**Pull request closed without merging**
